---
title: "Multiple Linear Regression Smoking Variables"
author: "Alessandra"
date: "2026-04-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(UsingR)
library(Bolstad)
babies_df <- babies
babies_df
```

```{r}
#this is with all of the subjects with missing/unsure values removed
babies_df = subset(babies_df, wt != 999 & parity != 99 & race != 99 & age != 99 & ed != 9 & ht != 99 & wt1 != 999 & drace != 99 & dage != 99 & ded != 9 & dht != 99 & dwt != 999 & inc != 99 & smoke != 9 & time != 99 & time != 98 & number != 99 & number != 98)
```

```{r}
#this just removes subjects with unsure values for the smoking model
babies_smoke_df = subset(babies_df, wt != 999 & smoke != 9 & time != 99 & time != 98 & number != 99 & number != 98)


```

```{r}
pairs(babies_smoke_df, upper.panel = panel.smooth)
```

```{r}
#modeling the smoking variables: birth weight, smoke, time, and number
b0 = rep(0, 4)
V0 = 1e4 * diag(rep(1, 4))
fit = bayes.lm(wt ~ smoke + time + number, data = babies_smoke_df, prior = list(b0 = b0, V0 = V0))
```
```{r}
#extracting mean and variance
b1 = fit$post.mean
V1 = fit$post.var
```

```{r}
V1_extracted <- V1[-1, -1] #removing intercept row and column
V1_extracted

b1_reduced <- b1[-1] #removing intercept value
```

```{r}
summary(fit)
```


```{r}
credible_region <- t(b1_reduced) %*% solve(V1_extracted) %*% b1_reduced
credible_region
```


Now I need to compare 40.65325 with the value for the 0.975 percentile of the chi-square distribution (7.815).

Since 40.6532 is greater than 7.815, this means that 0 is not in the credible region.







